export const FA_ERRORS: Record<string, string> = {
  'User not found': 'کاربر یافت نشد',
  'user not found': 'کاربر یافت نشد',
  'Customer not found': 'مشتری یافت نشد',
  'Not a customer': 'مشتری نیست',
  'Barber not found': 'آرایشگر یافت نشد',
  'Barber profile not found': 'پروفایل آرایشگر یافت نشد',
  'Barber has no linked user': 'آرایشگر کاربر مرتبط ندارد',
  'Barbershop not found': 'آرایشگاه یافت نشد',
  'Service not found': 'خدمت یافت نشد',
  'Appointment not found': 'نوبت یافت نشد',
  'Certificate not found': 'مدرک یافت نشد',
  'Educational not found': 'محتوای آموزشی یافت نشد',
  'Location not found': 'موقعیت یافت نشد',
  'Location not found for this barber': 'موقعیتی برای این آرایشگر یافت نشد',
  'Notification not found': 'اعلان یافت نشد',
  'Setting not found': 'تنظیم یافت نشد',
  'Barber not available': 'آرایشگر در دسترس نیست',
  'Barber on holiday': 'آرایشگر در مرخصی است',
  'barberId required': 'شناسه آرایشگر الزامی است',
  'userId required': 'شناسه کاربر الزامی است',
  'barberId or userId required': 'شناسه آرایشگر یا کاربر الزامی است',
  'provide only one of barberId or userId': 'فقط یکی از شناسه آرایشگر یا کاربر را وارد کنید',
  'Service does not belong to barber': 'این خدمت متعلق به این آرایشگر نیست',
  'Date cannot be in the past': 'تاریخ نمی‌تواند در گذشته باشد',
  'Cannot book in the past': 'رزرو در گذشته امکان‌پذیر نیست',
  'date must be YYYY-MM-DD': 'قالب تاریخ باید YYYY-MM-DD باشد',
  'Invalid time': 'زمان نامعتبر است',
  'startTime must be before endTime': 'زمان شروع باید قبل از زمان پایان باشد',
  'startTime/endTime must match date': 'زمان شروع/پایان باید با تاریخ مطابقت داشته باشد',
  'Slot already booked': 'این ساعت قبلا رزرو شده است',
  'Unauthorized': 'احراز هویت لازم است',
  'unauthorized': 'احراز هویت لازم است',
  'invalid credentials': 'نام کاربری یا رمز عبور اشتباه است',
  'account disabled': 'حساب کاربری غیرفعال است',
  'invalid token': 'توکن نامعتبر است',
  'invalid refresh token': 'توکن تمدید نامعتبر است',
  'refresh token revoked': 'توکن تمدید باطل شده است',
  'refresh token expired': 'توکن تمدید منقضی شده است',
  'invalid reset token': 'توکن بازیابی نامعتبر است',
  'reset token already used': 'توکن بازیابی قبلا استفاده شده است',
  'reset token expired': 'توکن بازیابی منقضی شده است',
  'email or username required': 'ایمیل یا نام کاربری الزامی است',
  'passwords do not match': 'رمزهای عبور مطابقت ندارند',
  'username already taken': 'این نام کاربری قبلا گرفته شده است',
  'email already taken': 'این ایمیل قبلا ثبت شده است',
  'nationalCode already registered': 'این کد ملی قبلا ثبت شده است',
  'key already exists': 'این کلید قبلا وجود دارد',
  'Barber profile already exists for this user': 'برای این کاربر پروفایل آرایشگر وجود دارد',
  'Location already exists for this barber': 'برای این آرایشگر موقعیت ثبت شده است',
  'duplicate holidays': 'تعطیلات تکراری است',
  'duplicate serviceId': 'شناسه خدمت تکراری است',
  'duplicate workingDays': 'روزهای کاری تکراری است',
  'invalid breakTime': 'زمان استراحت نامعتبر است',
  'invalid file extension': 'پسوند فایل نامعتبر است',
  'video file required': 'فایل ویدیو الزامی است',
  'video too large (max 100MB)': 'حجم ویدیو زیاد است (حداکثر ۱۰۰ مگابایت)',
  'expiryDate must be after issueDate': 'تاریخ انقضا باید بعد از تاریخ صدور باشد',
  'status must be active|inactive': 'وضعیت باید active یا inactive باشد',
  'cannot create barber for another user': 'نمی‌توانید برای کاربر دیگر آرایشگر بسازید',
  'cannot create service for another barber': 'نمی‌توانید برای آرایشگر دیگر خدمت بسازید',
  'cannot delete own account': 'نمی‌توانید حساب خود را حذف کنید',
  'cannot deactivate own account': 'نمی‌توانید حساب خود را غیرفعال کنید',
  'only super_admin can delete super_admin': 'فقط سوپرادمین می‌تواند سوپرادمین را حذف کند',
  'not allowed for this barber': 'برای این آرایشگر مجاز نیست',
  'not allowed for this location': 'برای این موقعیت مجاز نیست',
  'not allowed for this user': 'برای این کاربر مجاز نیست',
  'Not allowed to cancel': 'لغو این نوبت مجاز نیست',
  'not allowed to delete this barber': 'حذف این آرایشگر مجاز نیست',
  'not allowed to modify this service': 'ویرایش این خدمت مجاز نیست',
  'not allowed to update this barber': 'ویرایش این آرایشگر مجاز نیست',
  'Not allowed to view this appointment': 'مشاهده این نوبت مجاز نیست',
  'Only barber or admin can update status': 'فقط آرایشگر یا مدیر می‌تواند وضعیت را تغییر دهد',
  'Only owner or admin can delete': 'فقط مالک یا مدیر می‌تواند حذف کند',
  'Only owner or admin can edit': 'فقط مالک یا مدیر می‌تواند ویرایش کند',
  'barber profile required': 'پروفایل آرایشگر الزامی است',
  'nationalCode must be 10 digits': 'کد ملی باید ۱۰ رقم باشد',
  'phoneNumber must be valid (09xxxxxxxxx)': 'شماره موبایل معتبر نیست (09xxxxxxxxx)',
  'Bad Request': 'درخواست نامعتبر است',
  'Forbidden': 'دسترسی مجاز نیست',
  'Forbidden resource': 'دسترسی به این منبع مجاز نیست',
  'Not Found': 'یافت نشد',
  'Conflict': 'تداخل در اطلاعات',
  'Internal Server Error': 'خطای داخلی سرور',
};

const FA_PATTERNS: Array<[RegExp, string]> = [
  [/^Barber not working on (.+)$/, 'آرایشگر در روز $1 کار نمی‌کند'],
  [/^No working hours for (.+)$/, 'ساعات کاری برای $1 ثبت نشده است'],
  [/^Slot outside working hours (.+)$/, 'ساعت خارج از ساعات کاری است ($1)'],
  [/^Slot overlaps break time (.+)$/, 'ساعت با زمان استراحت تداخل دارد ($1)'],
  [/^Cannot cancel appointment with status (.+)$/, 'لغو نوبت با وضعیت $1 امکان‌پذیر نیست'],
  [/^Cannot cancel with status (.+)$/, 'لغو با وضعیت $1 امکان‌پذیر نیست'],
  [/^Cannot transition from (.+) to (.+)$/, 'تغییر وضعیت از $1 به $2 امکان‌پذیر نیست'],
  [/^Duration must be (\d+) minutes$/, 'مدت زمان باید $1 دقیقه باشد'],
  [/^invalid day (.+) in breakTime$/, 'روز $1 در زمان استراحت نامعتبر است'],
  [/^invalid day (.+)$/, 'روز $1 نامعتبر است'],
  [/^invalid time for (.+), use HH:mm$/, 'زمان $1 نامعتبر است، از قالب HH:mm استفاده کنید'],
  [/^start must be before end for (.+)$/, 'زمان شروع $1 باید قبل از پایان باشد'],
  [/^workingHours day (.+) not in workingDays$/, 'روز $1 در روزهای کاری نیست'],
  [/^breakTime day (.+) not in workingDays$/, 'روز استراحت $1 در روزهای کاری نیست'],
  [/^invalid workingDay (.+)$/, 'روز کاری $1 نامعتبر است'],
  [/^invalid breakTime for (.+), use HH:mm with start < end$/, 'زمان استراحت $1 نامعتبر است'],
  [/^unsupported video type (.+)$/, 'نوع ویدیو پشتیبانی نمی‌شود ($1)'],
  [/^Service (.+) not found$/, 'خدمت $1 یافت نشد'],
];

const FA_VALIDATION_FRAGMENTS: Array<[RegExp, string]> = [
  [/should not be empty/i, 'نباید خالی باشد'],
  [/must be a string/i, 'باید رشته باشد'],
  [/must be an email/i, 'باید ایمیل معتبر باشد'],
  [/must be a number/i, 'باید عدد باشد'],
  [/must be a boolean/i, 'باید بولین باشد'],
  [/property (.+) should not exist/i, 'ویژگی $1 نباید وجود داشته باشد'],
];

export function toFa(message: string): string {
  const exact = FA_ERRORS[message];
  if (exact) return exact;
  for (const [re, fa] of FA_PATTERNS) {
    if (re.test(message)) return message.replace(re, fa);
  }
  for (const [re, fa] of FA_VALIDATION_FRAGMENTS) {
    if (re.test(message)) return message.replace(re, fa);
  }
  return message;
}
